# Generated by Django 5.2.4 on 2025-07-23 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=20)),
                ('jornada', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('seccion', models.CharField(max_length=20)),
                ('docente', models.CharField(blank=True, max_length=200, null=True)),
                ('virtual_sincronica', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='oferta.asignatura')),
            ],
        ),
    ]
