# Generated by Django 5.2.4 on 2025-07-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='virtual_sincronica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
