# Generated by Django 5.2.4 on 2025-10-24 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0002_alter_asignatura_virtual_sincronica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('asignaturas', models.ManyToManyField(related_name='en_horarios_guardados', to='oferta.asignatura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_guardados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modificado_en'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
    ]
